"""Add completed_date column

Revision ID: eac02c0945a4
Revises: 8e66bd8d22d8
Create Date: 2025-04-18 16:03:45.687204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac02c0945a4'
down_revision = '8e66bd8d22d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('repeat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('repeat')
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###
